### ISSUE TITLE
2.0 is not compatible with dojo v1.7.2 in NodeJS

### ISSUE THREAD

**Issue by gitawego** [requirejs/requirejs#288]
I defined dojo as a package:

<pre>
requirejs.config({
            nodeRequire:require,
            baseUrl:__dirname,
            packages:[
                {
                    name:"dojo",
                    location:"./node_modules/dojo"
                },
                {
                    name:"dojox",
                    location:"./node_modules/dojox"
                }
            ]
        });
</pre>

but when I tried to require it via:

<pre>
requirejs(["dojo"]);
</pre>

NodeJs throws such error:

<pre>
/media/backup/workspace/repository/v7.2/plusnode/node_modules/requirejs/bin/r.js:1861
        throw err;
              ^
Error: Calling node's require("0") failed with error: Error: Cannot find module '0'
    at /media/backup/workspace/repository/v7.2/plusnode/node_modules/requirejs/bin/r.js:2211:27
    at Object.execCb (/media/backup/workspace/repository/v7.2/plusnode/node_modules/requirejs/bin/r.js:1725:33)
    at Object.check (/media/backup/workspace/repository/v7.2/plusnode/node_modules/requirejs/bin/r.js:1085:51)
    at Object.enable (/media/backup/workspace/repository/v7.2/plusnode/node_modules/requirejs/bin/r.js:1279:22)
    at Object.init (/media/backup/workspace/repository/v7.2/plusnode/node_modules/requirejs/bin/r.js:982:26)
    at callGetModule (/media/backup/workspace/repository/v7.2/plusnode/node_modules/requirejs/bin/r.js:1304:59)
    at Object.completeLoad (/media/backup/workspace/repository/v7.2/plusnode/node_modules/requirejs/bin/r.js:1601:21)
    at Function.load (/media/backup/workspace/repository/v7.2/plusnode/node_modules/requirejs/bin/r.js:2221:17)
    at Object.load (/media/backup/workspace/repository/v7.2/plusnode/node_modules/requirejs/bin/r.js:1714:21)
    at Object.load (/media/backup/workspace/repository/v7.2/plusnode/node_modules/requirejs/bin/r.js:1042:29)
</pre>

it worked with v1.0.8
